# Form implementation generated from reading ui file 'ui/checkout/checkout_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_AtlasPressCheckoutDialog(object):
    def setupUi(self, AtlasPressCheckoutDialog):
        AtlasPressCheckoutDialog.setObjectName("AtlasPressCheckoutDialog")
        AtlasPressCheckoutDialog.resize(560, 440)
        AtlasPressCheckoutDialog.setMinimumSize(QtCore.QSize(520, 400))
        self.rootLayout = QtWidgets.QVBoxLayout(AtlasPressCheckoutDialog)
        self.rootLayout.setContentsMargins(20, 18, 20, 16)
        self.rootLayout.setSpacing(14)
        self.rootLayout.setObjectName("rootLayout")
        self.headerLabel = QtWidgets.QLabel(parent=AtlasPressCheckoutDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.headerLabel.setFont(font)
        self.headerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headerLabel.setObjectName("headerLabel")
        self.rootLayout.addWidget(self.headerLabel)
        self.stepIndicatorLabel = QtWidgets.QLabel(parent=AtlasPressCheckoutDialog)
        self.stepIndicatorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.stepIndicatorLabel.setObjectName("stepIndicatorLabel")
        self.rootLayout.addWidget(self.stepIndicatorLabel)
        self.dividerLine = QtWidgets.QFrame(parent=AtlasPressCheckoutDialog)
        self.dividerLine.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.dividerLine.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.dividerLine.setObjectName("dividerLine")
        self.rootLayout.addWidget(self.dividerLine)
        self.checkoutStackedWidget = QtWidgets.QStackedWidget(parent=AtlasPressCheckoutDialog)
        self.checkoutStackedWidget.setObjectName("checkoutStackedWidget")
        self.checkoutLoadingPage = QtWidgets.QWidget()
        self.checkoutLoadingPage.setObjectName("checkoutLoadingPage")
        self.checkoutLoadingLayout = QtWidgets.QVBoxLayout(self.checkoutLoadingPage)
        self.checkoutLoadingLayout.setSpacing(12)
        self.checkoutLoadingLayout.setObjectName("checkoutLoadingLayout")
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.checkoutLoadingLayout.addItem(spacerItem)
        self.checkoutLoadingSpinnerLabel = QtWidgets.QLabel(parent=self.checkoutLoadingPage)
        self.checkoutLoadingSpinnerLabel.setMinimumSize(QtCore.QSize(0, 36))
        self.checkoutLoadingSpinnerLabel.setText("")
        self.checkoutLoadingSpinnerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.checkoutLoadingSpinnerLabel.setObjectName("checkoutLoadingSpinnerLabel")
        self.checkoutLoadingLayout.addWidget(self.checkoutLoadingSpinnerLabel)
        self.checkoutLoadingTextLabel = QtWidgets.QLabel(parent=self.checkoutLoadingPage)
        self.checkoutLoadingTextLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.checkoutLoadingTextLabel.setWordWrap(True)
        self.checkoutLoadingTextLabel.setObjectName("checkoutLoadingTextLabel")
        self.checkoutLoadingLayout.addWidget(self.checkoutLoadingTextLabel)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.checkoutLoadingLayout.addItem(spacerItem1)
        self.checkoutStackedWidget.addWidget(self.checkoutLoadingPage)
        self.checkoutStatusPage = QtWidgets.QWidget()
        self.checkoutStatusPage.setObjectName("checkoutStatusPage")
        self.checkoutStatusLayout = QtWidgets.QVBoxLayout(self.checkoutStatusPage)
        self.checkoutStatusLayout.setSpacing(12)
        self.checkoutStatusLayout.setObjectName("checkoutStatusLayout")
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.checkoutStatusLayout.addItem(spacerItem2)
        self.paymentStatusIconLabel = QtWidgets.QLabel(parent=self.checkoutStatusPage)
        self.paymentStatusIconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.paymentStatusIconLabel.setObjectName("paymentStatusIconLabel")
        self.checkoutStatusLayout.addWidget(self.paymentStatusIconLabel)
        self.paymentStatusTitleLabel = QtWidgets.QLabel(parent=self.checkoutStatusPage)
        self.paymentStatusTitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.paymentStatusTitleLabel.setWordWrap(True)
        self.paymentStatusTitleLabel.setObjectName("paymentStatusTitleLabel")
        self.checkoutStatusLayout.addWidget(self.paymentStatusTitleLabel)
        self.paymentStatusMessageLabel = QtWidgets.QLabel(parent=self.checkoutStatusPage)
        self.paymentStatusMessageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.paymentStatusMessageLabel.setWordWrap(True)
        self.paymentStatusMessageLabel.setObjectName("paymentStatusMessageLabel")
        self.checkoutStatusLayout.addWidget(self.paymentStatusMessageLabel)
        self.publicOrderIdLabel = QtWidgets.QLabel(parent=self.checkoutStatusPage)
        self.publicOrderIdLabel.setVisible(False)
        self.publicOrderIdLabel.setText("")
        self.publicOrderIdLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.publicOrderIdLabel.setTextInteractionFlags(
            QtCore.Qt.TextInteractionFlag.TextSelectableByMouse
        )
        self.publicOrderIdLabel.setWordWrap(True)
        self.publicOrderIdLabel.setObjectName("publicOrderIdLabel")
        self.checkoutStatusLayout.addWidget(self.publicOrderIdLabel)
        self.paymentRefreshWarningLabel = QtWidgets.QLabel(parent=self.checkoutStatusPage)
        self.paymentRefreshWarningLabel.setVisible(False)
        self.paymentRefreshWarningLabel.setText("")
        self.paymentRefreshWarningLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.paymentRefreshWarningLabel.setWordWrap(True)
        self.paymentRefreshWarningLabel.setObjectName("paymentRefreshWarningLabel")
        self.checkoutStatusLayout.addWidget(self.paymentRefreshWarningLabel)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.checkoutStatusLayout.addItem(spacerItem3)
        self.checkoutStackedWidget.addWidget(self.checkoutStatusPage)
        self.checkoutErrorPage = QtWidgets.QWidget()
        self.checkoutErrorPage.setObjectName("checkoutErrorPage")
        self.checkoutErrorLayout = QtWidgets.QVBoxLayout(self.checkoutErrorPage)
        self.checkoutErrorLayout.setSpacing(12)
        self.checkoutErrorLayout.setObjectName("checkoutErrorLayout")
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.checkoutErrorLayout.addItem(spacerItem4)
        self.checkoutErrorTitleLabel = QtWidgets.QLabel(parent=self.checkoutErrorPage)
        self.checkoutErrorTitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.checkoutErrorTitleLabel.setWordWrap(True)
        self.checkoutErrorTitleLabel.setObjectName("checkoutErrorTitleLabel")
        self.checkoutErrorLayout.addWidget(self.checkoutErrorTitleLabel)
        self.checkoutErrorMessageLabel = QtWidgets.QLabel(parent=self.checkoutErrorPage)
        self.checkoutErrorMessageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.checkoutErrorMessageLabel.setWordWrap(True)
        self.checkoutErrorMessageLabel.setObjectName("checkoutErrorMessageLabel")
        self.checkoutErrorLayout.addWidget(self.checkoutErrorMessageLabel)
        self.checkoutErrorDetailsLabel = QtWidgets.QLabel(parent=self.checkoutErrorPage)
        self.checkoutErrorDetailsLabel.setVisible(False)
        self.checkoutErrorDetailsLabel.setText("")
        self.checkoutErrorDetailsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.checkoutErrorDetailsLabel.setWordWrap(True)
        self.checkoutErrorDetailsLabel.setObjectName("checkoutErrorDetailsLabel")
        self.checkoutErrorLayout.addWidget(self.checkoutErrorDetailsLabel)
        spacerItem5 = QtWidgets.QSpacerItem(
            20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.checkoutErrorLayout.addItem(spacerItem5)
        self.checkoutStackedWidget.addWidget(self.checkoutErrorPage)
        self.rootLayout.addWidget(self.checkoutStackedWidget)
        self.buttonsActions = QtWidgets.QDialogButtonBox(parent=AtlasPressCheckoutDialog)
        self.buttonsActions.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonsActions.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Close
            | QtWidgets.QDialogButtonBox.StandardButton.Retry
        )
        self.buttonsActions.setObjectName("buttonsActions")
        self.rootLayout.addWidget(self.buttonsActions)

        self.retranslateUi(AtlasPressCheckoutDialog)
        self.checkoutStackedWidget.setCurrentIndex(0)
        self.buttonsActions.rejected.connect(AtlasPressCheckoutDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AtlasPressCheckoutDialog)

    def retranslateUi(self, AtlasPressCheckoutDialog):
        _translate = QtCore.QCoreApplication.translate
        AtlasPressCheckoutDialog.setWindowTitle(
            _translate("AtlasPressCheckoutDialog", "Atlas Press — Secure Checkout")
        )
        self.headerLabel.setText(
            _translate("AtlasPressCheckoutDialog", "🗺️  Print & Order Your Map")
        )
        self.stepIndicatorLabel.setText(
            _translate("AtlasPressCheckoutDialog", "Step 4 of 4 — Secure Checkout")
        )
        self.stepIndicatorLabel.setStyleSheet(
            _translate("AtlasPressCheckoutDialog", "color: palette(text); font-size: 11px;")
        )
        self.dividerLine.setStyleSheet(_translate("AtlasPressCheckoutDialog", "color: #dddddd;"))
        self.checkoutLoadingTextLabel.setText(
            _translate("AtlasPressCheckoutDialog", "Preparing secure checkout...")
        )
        self.checkoutLoadingTextLabel.setStyleSheet(
            _translate("AtlasPressCheckoutDialog", "color: palette(text); font-size: 12px;")
        )
        self.paymentStatusIconLabel.setText(_translate("AtlasPressCheckoutDialog", "..."))
        self.paymentStatusIconLabel.setStyleSheet(
            _translate(
                "AtlasPressCheckoutDialog",
                "color: palette(text); font-size: 32px; font-weight: bold;",
            )
        )
        self.paymentStatusTitleLabel.setText(
            _translate("AtlasPressCheckoutDialog", "Waiting for payment confirmation")
        )
        self.paymentStatusTitleLabel.setStyleSheet(
            _translate(
                "AtlasPressCheckoutDialog",
                "color: palette(text); font-size: 16px; font-weight: bold;",
            )
        )
        self.paymentStatusMessageLabel.setText(
            _translate(
                "AtlasPressCheckoutDialog",
                "Complete payment in your browser. AtlasPress will update automatically.",
            )
        )
        self.paymentStatusMessageLabel.setStyleSheet(
            _translate("AtlasPressCheckoutDialog", "color: palette(text); font-size: 11px;")
        )
        self.publicOrderIdLabel.setStyleSheet(
            _translate(
                "AtlasPressCheckoutDialog",
                "color: palette(text); font-size: 11px; font-weight: bold;",
            )
        )
        self.paymentRefreshWarningLabel.setStyleSheet(
            _translate("AtlasPressCheckoutDialog", "color: #d97706; font-size: 10px;")
        )
        self.checkoutErrorTitleLabel.setText(
            _translate("AtlasPressCheckoutDialog", "Could not prepare checkout")
        )
        self.checkoutErrorTitleLabel.setStyleSheet(
            _translate(
                "AtlasPressCheckoutDialog", "color: #d32f2f; font-size: 15px; font-weight: bold;"
            )
        )
        self.checkoutErrorMessageLabel.setText(
            _translate("AtlasPressCheckoutDialog", "You can retry or close this window.")
        )
        self.checkoutErrorMessageLabel.setStyleSheet(
            _translate("AtlasPressCheckoutDialog", "color: palette(text); font-size: 11px;")
        )
        self.checkoutErrorDetailsLabel.setStyleSheet(
            _translate("AtlasPressCheckoutDialog", "color: palette(text); font-size: 10px;")
        )
