# Form implementation generated from reading ui file 'ui/shipping/shipping_address_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_AtlasPressShippingDialog(object):
    def setupUi(self, AtlasPressShippingDialog):
        AtlasPressShippingDialog.setObjectName("AtlasPressShippingDialog")
        AtlasPressShippingDialog.resize(560, 640)
        AtlasPressShippingDialog.setMinimumSize(QtCore.QSize(540, 600))
        self.rootLayout = QtWidgets.QVBoxLayout(AtlasPressShippingDialog)
        self.rootLayout.setContentsMargins(20, 18, 20, 16)
        self.rootLayout.setSpacing(14)
        self.rootLayout.setObjectName("rootLayout")
        self.headerLabel = QtWidgets.QLabel(parent=AtlasPressShippingDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.headerLabel.setFont(font)
        self.headerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headerLabel.setObjectName("headerLabel")
        self.rootLayout.addWidget(self.headerLabel)
        self.stepIndicatorLabel = QtWidgets.QLabel(parent=AtlasPressShippingDialog)
        self.stepIndicatorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.stepIndicatorLabel.setObjectName("stepIndicatorLabel")
        self.rootLayout.addWidget(self.stepIndicatorLabel)
        self.dividerLine = QtWidgets.QFrame(parent=AtlasPressShippingDialog)
        self.dividerLine.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.dividerLine.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.dividerLine.setObjectName("dividerLine")
        self.rootLayout.addWidget(self.dividerLine)
        self.dialogStackedWidget = QtWidgets.QStackedWidget(parent=AtlasPressShippingDialog)
        self.dialogStackedWidget.setObjectName("dialogStackedWidget")
        self.dialogLoadingPage = QtWidgets.QWidget()
        self.dialogLoadingPage.setObjectName("dialogLoadingPage")
        self.dialogLoadingLayout = QtWidgets.QVBoxLayout(self.dialogLoadingPage)
        self.dialogLoadingLayout.setSpacing(12)
        self.dialogLoadingLayout.setObjectName("dialogLoadingLayout")
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.dialogLoadingLayout.addItem(spacerItem)
        self.dialogLoadingSpinnerLabel = QtWidgets.QLabel(parent=self.dialogLoadingPage)
        self.dialogLoadingSpinnerLabel.setMinimumSize(QtCore.QSize(0, 36))
        self.dialogLoadingSpinnerLabel.setText("")
        self.dialogLoadingSpinnerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dialogLoadingSpinnerLabel.setObjectName("dialogLoadingSpinnerLabel")
        self.dialogLoadingLayout.addWidget(self.dialogLoadingSpinnerLabel)
        self.dialogLoadingTextLabel = QtWidgets.QLabel(parent=self.dialogLoadingPage)
        self.dialogLoadingTextLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dialogLoadingTextLabel.setObjectName("dialogLoadingTextLabel")
        self.dialogLoadingLayout.addWidget(self.dialogLoadingTextLabel)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.dialogLoadingLayout.addItem(spacerItem1)
        self.dialogStackedWidget.addWidget(self.dialogLoadingPage)
        self.dialogFormPage = QtWidgets.QWidget()
        self.dialogFormPage.setObjectName("dialogFormPage")
        self.dialogFormLayout = QtWidgets.QVBoxLayout(self.dialogFormPage)
        self.dialogFormLayout.setContentsMargins(0, 0, 0, 0)
        self.dialogFormLayout.setSpacing(0)
        self.dialogFormLayout.setObjectName("dialogFormLayout")
        self.formScrollArea = QtWidgets.QScrollArea(parent=self.dialogFormPage)
        self.formScrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.formScrollArea.setWidgetResizable(True)
        self.formScrollArea.setObjectName("formScrollArea")
        self.formScrollContents = QtWidgets.QWidget()
        self.formScrollContents.setGeometry(QtCore.QRect(0, 0, 503, 479))
        self.formScrollContents.setObjectName("formScrollContents")
        self.formScrollLayout = QtWidgets.QVBoxLayout(self.formScrollContents)
        self.formScrollLayout.setContentsMargins(0, 2, 4, 4)
        self.formScrollLayout.setSpacing(14)
        self.formScrollLayout.setObjectName("formScrollLayout")
        self.recipientGroupBox = QtWidgets.QGroupBox(parent=self.formScrollContents)
        self.recipientGroupBox.setObjectName("recipientGroupBox")
        self.recipientLayout = QtWidgets.QVBoxLayout(self.recipientGroupBox)
        self.recipientLayout.setSpacing(8)
        self.recipientLayout.setObjectName("recipientLayout")
        self.nameFieldLayout = QtWidgets.QVBoxLayout()
        self.nameFieldLayout.setSpacing(2)
        self.nameFieldLayout.setObjectName("nameFieldLayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.nameLabel = QtWidgets.QLabel(parent=self.recipientGroupBox)
        self.nameLabel.setObjectName("nameLabel")
        self.hboxlayout.addWidget(self.nameLabel)
        self.nameRequiredMark = QtWidgets.QLabel(parent=self.recipientGroupBox)
        self.nameRequiredMark.setObjectName("nameRequiredMark")
        self.hboxlayout.addWidget(self.nameRequiredMark)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.hboxlayout.addItem(spacerItem2)
        self.nameFieldLayout.addLayout(self.hboxlayout)
        self.nameLineEdit = QtWidgets.QLineEdit(parent=self.recipientGroupBox)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.nameFieldLayout.addWidget(self.nameLineEdit)
        self.nameErrorLabel = QtWidgets.QLabel(parent=self.recipientGroupBox)
        self.nameErrorLabel.setVisible(False)
        self.nameErrorLabel.setObjectName("nameErrorLabel")
        self.nameFieldLayout.addWidget(self.nameErrorLabel)
        self.recipientLayout.addLayout(self.nameFieldLayout)
        self.emailFieldLayout = QtWidgets.QVBoxLayout()
        self.emailFieldLayout.setSpacing(2)
        self.emailFieldLayout.setObjectName("emailFieldLayout")
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.emailLabel = QtWidgets.QLabel(parent=self.recipientGroupBox)
        self.emailLabel.setObjectName("emailLabel")
        self.hboxlayout1.addWidget(self.emailLabel)
        self.emailRequiredMark = QtWidgets.QLabel(parent=self.recipientGroupBox)
        self.emailRequiredMark.setObjectName("emailRequiredMark")
        self.hboxlayout1.addWidget(self.emailRequiredMark)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.hboxlayout1.addItem(spacerItem3)
        self.emailFieldLayout.addLayout(self.hboxlayout1)
        self.emailLineEdit = QtWidgets.QLineEdit(parent=self.recipientGroupBox)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.emailFieldLayout.addWidget(self.emailLineEdit)
        self.emailErrorLabel = QtWidgets.QLabel(parent=self.recipientGroupBox)
        self.emailErrorLabel.setVisible(False)
        self.emailErrorLabel.setObjectName("emailErrorLabel")
        self.emailFieldLayout.addWidget(self.emailErrorLabel)
        self.recipientLayout.addLayout(self.emailFieldLayout)
        self.formScrollLayout.addWidget(self.recipientGroupBox)
        self.addressGroupBox = QtWidgets.QGroupBox(parent=self.formScrollContents)
        self.addressGroupBox.setObjectName("addressGroupBox")
        self.addressLayout = QtWidgets.QVBoxLayout(self.addressGroupBox)
        self.addressLayout.setSpacing(8)
        self.addressLayout.setObjectName("addressLayout")
        self.countryFieldLayout = QtWidgets.QVBoxLayout()
        self.countryFieldLayout.setSpacing(2)
        self.countryFieldLayout.setObjectName("countryFieldLayout")
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.countryLabel = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.countryLabel.setObjectName("countryLabel")
        self.hboxlayout2.addWidget(self.countryLabel)
        self.countryRequiredMark = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.countryRequiredMark.setObjectName("countryRequiredMark")
        self.hboxlayout2.addWidget(self.countryRequiredMark)
        spacerItem4 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.hboxlayout2.addItem(spacerItem4)
        self.countryFieldLayout.addLayout(self.hboxlayout2)
        self.countryComboBox = QtWidgets.QComboBox(parent=self.addressGroupBox)
        self.countryComboBox.setEditable(True)
        self.countryComboBox.setObjectName("countryComboBox")
        self.countryFieldLayout.addWidget(self.countryComboBox)
        self.countryErrorLabel = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.countryErrorLabel.setVisible(False)
        self.countryErrorLabel.setObjectName("countryErrorLabel")
        self.countryFieldLayout.addWidget(self.countryErrorLabel)
        self.addressLayout.addLayout(self.countryFieldLayout)
        self.address1FieldLayout = QtWidgets.QVBoxLayout()
        self.address1FieldLayout.setSpacing(2)
        self.address1FieldLayout.setObjectName("address1FieldLayout")
        self.hboxlayout3 = QtWidgets.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.address1Label = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.address1Label.setObjectName("address1Label")
        self.hboxlayout3.addWidget(self.address1Label)
        self.address1RequiredMark = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.address1RequiredMark.setObjectName("address1RequiredMark")
        self.hboxlayout3.addWidget(self.address1RequiredMark)
        spacerItem5 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.hboxlayout3.addItem(spacerItem5)
        self.address1FieldLayout.addLayout(self.hboxlayout3)
        self.address1LineEdit = QtWidgets.QLineEdit(parent=self.addressGroupBox)
        self.address1LineEdit.setObjectName("address1LineEdit")
        self.address1FieldLayout.addWidget(self.address1LineEdit)
        self.address1ErrorLabel = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.address1ErrorLabel.setVisible(False)
        self.address1ErrorLabel.setObjectName("address1ErrorLabel")
        self.address1FieldLayout.addWidget(self.address1ErrorLabel)
        self.addressLayout.addLayout(self.address1FieldLayout)
        self.address2FieldLayout = QtWidgets.QVBoxLayout()
        self.address2FieldLayout.setSpacing(2)
        self.address2FieldLayout.setObjectName("address2FieldLayout")
        self.hboxlayout4 = QtWidgets.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.address2Label = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.address2Label.setObjectName("address2Label")
        self.hboxlayout4.addWidget(self.address2Label)
        self.address2OptionalLabel = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.address2OptionalLabel.setObjectName("address2OptionalLabel")
        self.hboxlayout4.addWidget(self.address2OptionalLabel)
        spacerItem6 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.hboxlayout4.addItem(spacerItem6)
        self.address2FieldLayout.addLayout(self.hboxlayout4)
        self.address2LineEdit = QtWidgets.QLineEdit(parent=self.addressGroupBox)
        self.address2LineEdit.setObjectName("address2LineEdit")
        self.address2FieldLayout.addWidget(self.address2LineEdit)
        self.addressLayout.addLayout(self.address2FieldLayout)
        self.cityPostalLayout = QtWidgets.QHBoxLayout()
        self.cityPostalLayout.setSpacing(12)
        self.cityPostalLayout.setObjectName("cityPostalLayout")
        self.cityFieldLayout = QtWidgets.QVBoxLayout()
        self.cityFieldLayout.setSpacing(2)
        self.cityFieldLayout.setObjectName("cityFieldLayout")
        self.hboxlayout5 = QtWidgets.QHBoxLayout()
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.cityLabel = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.cityLabel.setObjectName("cityLabel")
        self.hboxlayout5.addWidget(self.cityLabel)
        self.cityRequiredMark = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.cityRequiredMark.setObjectName("cityRequiredMark")
        self.hboxlayout5.addWidget(self.cityRequiredMark)
        spacerItem7 = QtWidgets.QSpacerItem(
            20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.hboxlayout5.addItem(spacerItem7)
        self.cityFieldLayout.addLayout(self.hboxlayout5)
        self.cityLineEdit = QtWidgets.QLineEdit(parent=self.addressGroupBox)
        self.cityLineEdit.setObjectName("cityLineEdit")
        self.cityFieldLayout.addWidget(self.cityLineEdit)
        self.cityErrorLabel = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.cityErrorLabel.setVisible(False)
        self.cityErrorLabel.setObjectName("cityErrorLabel")
        self.cityFieldLayout.addWidget(self.cityErrorLabel)
        self.cityPostalLayout.addLayout(self.cityFieldLayout)
        self.postalFieldLayout = QtWidgets.QVBoxLayout()
        self.postalFieldLayout.setSpacing(2)
        self.postalFieldLayout.setObjectName("postalFieldLayout")
        self.hboxlayout6 = QtWidgets.QHBoxLayout()
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.postalLabel = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.postalLabel.setObjectName("postalLabel")
        self.hboxlayout6.addWidget(self.postalLabel)
        self.postalRequiredMark = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.postalRequiredMark.setObjectName("postalRequiredMark")
        self.hboxlayout6.addWidget(self.postalRequiredMark)
        spacerItem8 = QtWidgets.QSpacerItem(
            20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.hboxlayout6.addItem(spacerItem8)
        self.postalFieldLayout.addLayout(self.hboxlayout6)
        self.postalLineEdit = QtWidgets.QLineEdit(parent=self.addressGroupBox)
        self.postalLineEdit.setObjectName("postalLineEdit")
        self.postalFieldLayout.addWidget(self.postalLineEdit)
        self.postalErrorLabel = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.postalErrorLabel.setVisible(False)
        self.postalErrorLabel.setObjectName("postalErrorLabel")
        self.postalFieldLayout.addWidget(self.postalErrorLabel)
        self.cityPostalLayout.addLayout(self.postalFieldLayout)
        self.addressLayout.addLayout(self.cityPostalLayout)
        self.stateFieldLayout = QtWidgets.QVBoxLayout()
        self.stateFieldLayout.setSpacing(2)
        self.stateFieldLayout.setObjectName("stateFieldLayout")
        self.hboxlayout7 = QtWidgets.QHBoxLayout()
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.stateLabel = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.stateLabel.setVisible(False)
        self.stateLabel.setObjectName("stateLabel")
        self.hboxlayout7.addWidget(self.stateLabel)
        self.stateRequiredMark = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.stateRequiredMark.setVisible(False)
        self.stateRequiredMark.setObjectName("stateRequiredMark")
        self.hboxlayout7.addWidget(self.stateRequiredMark)
        spacerItem9 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.hboxlayout7.addItem(spacerItem9)
        self.stateFieldLayout.addLayout(self.hboxlayout7)
        self.stateComboBox = QtWidgets.QComboBox(parent=self.addressGroupBox)
        self.stateComboBox.setVisible(False)
        self.stateComboBox.setEditable(True)
        self.stateComboBox.setObjectName("stateComboBox")
        self.stateFieldLayout.addWidget(self.stateComboBox)
        self.stateErrorLabel = QtWidgets.QLabel(parent=self.addressGroupBox)
        self.stateErrorLabel.setVisible(False)
        self.stateErrorLabel.setObjectName("stateErrorLabel")
        self.stateFieldLayout.addWidget(self.stateErrorLabel)
        self.addressLayout.addLayout(self.stateFieldLayout)
        self.formScrollLayout.addWidget(self.addressGroupBox)
        self.requiredNoteLabel = QtWidgets.QLabel(parent=self.formScrollContents)
        self.requiredNoteLabel.setObjectName("requiredNoteLabel")
        self.formScrollLayout.addWidget(self.requiredNoteLabel)
        self.formScrollArea.setWidget(self.formScrollContents)
        self.dialogFormLayout.addWidget(self.formScrollArea)
        self.dialogStackedWidget.addWidget(self.dialogFormPage)
        self.dialogErrorPage = QtWidgets.QWidget()
        self.dialogErrorPage.setObjectName("dialogErrorPage")
        self.dialogErrorLayout = QtWidgets.QVBoxLayout(self.dialogErrorPage)
        self.dialogErrorLayout.setSpacing(10)
        self.dialogErrorLayout.setObjectName("dialogErrorLayout")
        spacerItem10 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.dialogErrorLayout.addItem(spacerItem10)
        self.dialogErrorIconLabel = QtWidgets.QLabel(parent=self.dialogErrorPage)
        self.dialogErrorIconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dialogErrorIconLabel.setObjectName("dialogErrorIconLabel")
        self.dialogErrorLayout.addWidget(self.dialogErrorIconLabel)
        self.dialogErrorTitleLabel = QtWidgets.QLabel(parent=self.dialogErrorPage)
        self.dialogErrorTitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dialogErrorTitleLabel.setObjectName("dialogErrorTitleLabel")
        self.dialogErrorLayout.addWidget(self.dialogErrorTitleLabel)
        self.dialogErrorMessageLabel = QtWidgets.QLabel(parent=self.dialogErrorPage)
        self.dialogErrorMessageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dialogErrorMessageLabel.setWordWrap(True)
        self.dialogErrorMessageLabel.setObjectName("dialogErrorMessageLabel")
        self.dialogErrorLayout.addWidget(self.dialogErrorMessageLabel)
        self.dialogRetryLayout = QtWidgets.QHBoxLayout()
        self.dialogRetryLayout.setObjectName("dialogRetryLayout")
        spacerItem11 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.dialogRetryLayout.addItem(spacerItem11)
        self.dialogRetryButton = QtWidgets.QPushButton(parent=self.dialogErrorPage)
        self.dialogRetryButton.setObjectName("dialogRetryButton")
        self.dialogRetryLayout.addWidget(self.dialogRetryButton)
        spacerItem12 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.dialogRetryLayout.addItem(spacerItem12)
        self.dialogErrorLayout.addLayout(self.dialogRetryLayout)
        spacerItem13 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.dialogErrorLayout.addItem(spacerItem13)
        self.dialogStackedWidget.addWidget(self.dialogErrorPage)
        self.rootLayout.addWidget(self.dialogStackedWidget)
        self.buttonsActions = QtWidgets.QDialogButtonBox(parent=AtlasPressShippingDialog)
        self.buttonsActions.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonsActions.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.buttonsActions.setObjectName("buttonsActions")
        self.rootLayout.addWidget(self.buttonsActions)

        self.retranslateUi(AtlasPressShippingDialog)
        self.dialogStackedWidget.setCurrentIndex(1)
        self.buttonsActions.accepted.connect(AtlasPressShippingDialog.accept)  # type: ignore
        self.buttonsActions.rejected.connect(AtlasPressShippingDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AtlasPressShippingDialog)

    def retranslateUi(self, AtlasPressShippingDialog):
        _translate = QtCore.QCoreApplication.translate
        AtlasPressShippingDialog.setWindowTitle(
            _translate("AtlasPressShippingDialog", "Atlas Press — Shipping Information")
        )
        self.headerLabel.setText(
            _translate("AtlasPressShippingDialog", "🗺️  Print & Order Your Map")
        )
        self.stepIndicatorLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #666666; font-size: 11px;")
        )
        self.stepIndicatorLabel.setText(
            _translate("AtlasPressShippingDialog", "Step 2 of 3 — Shipping Information")
        )
        self.dividerLine.setStyleSheet(_translate("AtlasPressShippingDialog", "color: #dddddd;"))
        self.dialogLoadingTextLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #888888; font-size: 12px;")
        )
        self.dialogLoadingTextLabel.setText(
            _translate("AtlasPressShippingDialog", "Loading shipping countries…")
        )
        self.recipientGroupBox.setStyleSheet(
            _translate("AtlasPressShippingDialog", "QGroupBox { font-weight: bold; }")
        )
        self.recipientGroupBox.setTitle(_translate("AtlasPressShippingDialog", "Recipient"))
        self.nameLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "font-size: 11px; font-weight: 600;")
        )
        self.nameLabel.setText(_translate("AtlasPressShippingDialog", "Full Name"))
        self.nameRequiredMark.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #cc4444; font-weight: bold;")
        )
        self.nameRequiredMark.setText(_translate("AtlasPressShippingDialog", "*"))
        self.nameLineEdit.setPlaceholderText(
            _translate("AtlasPressShippingDialog", "e.g. Jane Smith")
        )
        self.nameErrorLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #cc4444; font-size: 10px;")
        )
        self.nameErrorLabel.setText(
            _translate("AtlasPressShippingDialog", "Full name is required.")
        )
        self.emailLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "font-size: 11px; font-weight: 600;")
        )
        self.emailLabel.setText(_translate("AtlasPressShippingDialog", "Email"))
        self.emailRequiredMark.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #cc4444; font-weight: bold;")
        )
        self.emailRequiredMark.setText(_translate("AtlasPressShippingDialog", "*"))
        self.emailLineEdit.setPlaceholderText(
            _translate("AtlasPressShippingDialog", "e.g. jane@example.com")
        )
        self.emailErrorLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #cc4444; font-size: 10px;")
        )
        self.emailErrorLabel.setText(
            _translate("AtlasPressShippingDialog", "A valid email address is required.")
        )
        self.addressGroupBox.setStyleSheet(
            _translate("AtlasPressShippingDialog", "QGroupBox { font-weight: bold; }")
        )
        self.addressGroupBox.setTitle(_translate("AtlasPressShippingDialog", "Shipping Address"))
        self.countryLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "font-size: 11px; font-weight: 600;")
        )
        self.countryLabel.setText(_translate("AtlasPressShippingDialog", "Country"))
        self.countryRequiredMark.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #cc4444; font-weight: bold;")
        )
        self.countryRequiredMark.setText(_translate("AtlasPressShippingDialog", "*"))
        self.countryErrorLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #cc4444; font-size: 10px;")
        )
        self.countryErrorLabel.setText(
            _translate("AtlasPressShippingDialog", "Please select a supported country.")
        )
        self.address1Label.setStyleSheet(
            _translate("AtlasPressShippingDialog", "font-size: 11px; font-weight: 600;")
        )
        self.address1Label.setText(_translate("AtlasPressShippingDialog", "Address Line 1"))
        self.address1RequiredMark.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #cc4444; font-weight: bold;")
        )
        self.address1RequiredMark.setText(_translate("AtlasPressShippingDialog", "*"))
        self.address1LineEdit.setPlaceholderText(
            _translate("AtlasPressShippingDialog", "e.g. 123 Main Street")
        )
        self.address1ErrorLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #cc4444; font-size: 10px;")
        )
        self.address1ErrorLabel.setText(
            _translate("AtlasPressShippingDialog", "Address line 1 is required.")
        )
        self.address2Label.setStyleSheet(
            _translate("AtlasPressShippingDialog", "font-size: 11px; font-weight: 600;")
        )
        self.address2Label.setText(_translate("AtlasPressShippingDialog", "Address Line 2"))
        self.address2OptionalLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #999999; font-size: 10px;")
        )
        self.address2OptionalLabel.setText(_translate("AtlasPressShippingDialog", "optional"))
        self.address2LineEdit.setPlaceholderText(
            _translate("AtlasPressShippingDialog", "e.g. Apt 4B, Suite 100")
        )
        self.cityLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "font-size: 11px; font-weight: 600;")
        )
        self.cityLabel.setText(_translate("AtlasPressShippingDialog", "City"))
        self.cityRequiredMark.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #cc4444; font-weight: bold;")
        )
        self.cityRequiredMark.setText(_translate("AtlasPressShippingDialog", "*"))
        self.cityLineEdit.setPlaceholderText(
            _translate("AtlasPressShippingDialog", "e.g. Montreal")
        )
        self.cityErrorLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #cc4444; font-size: 10px;")
        )
        self.cityErrorLabel.setText(_translate("AtlasPressShippingDialog", "City is required."))
        self.postalLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "font-size: 11px; font-weight: 600;")
        )
        self.postalLabel.setText(_translate("AtlasPressShippingDialog", "Postal / ZIP Code"))
        self.postalRequiredMark.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #cc4444; font-weight: bold;")
        )
        self.postalRequiredMark.setText(_translate("AtlasPressShippingDialog", "*"))
        self.postalLineEdit.setPlaceholderText(
            _translate("AtlasPressShippingDialog", "e.g. H2X 1Y4")
        )
        self.postalErrorLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #cc4444; font-size: 10px;")
        )
        self.postalErrorLabel.setText(
            _translate("AtlasPressShippingDialog", "Postal code is required.")
        )
        self.stateLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "font-size: 11px; font-weight: 600;")
        )
        self.stateLabel.setText(_translate("AtlasPressShippingDialog", "State / Province"))
        self.stateRequiredMark.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #cc4444; font-weight: bold;")
        )
        self.stateRequiredMark.setText(_translate("AtlasPressShippingDialog", "*"))
        self.stateErrorLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #cc4444; font-size: 10px;")
        )
        self.stateErrorLabel.setText(
            _translate("AtlasPressShippingDialog", "Please select a state / province.")
        )
        self.requiredNoteLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #999999; font-size: 10px;")
        )
        self.requiredNoteLabel.setText(_translate("AtlasPressShippingDialog", "* Required fields"))
        self.dialogErrorIconLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "font-size: 28px;")
        )
        self.dialogErrorIconLabel.setText(_translate("AtlasPressShippingDialog", "⚠️"))
        self.dialogErrorTitleLabel.setStyleSheet(
            _translate(
                "AtlasPressShippingDialog", "font-size: 13px; font-weight: bold; color: #333;"
            )
        )
        self.dialogErrorTitleLabel.setText(
            _translate("AtlasPressShippingDialog", "Could not load shipping countries")
        )
        self.dialogErrorMessageLabel.setStyleSheet(
            _translate("AtlasPressShippingDialog", "color: #666666; font-size: 11px;")
        )
        self.dialogErrorMessageLabel.setText(
            _translate("AtlasPressShippingDialog", "Please check your connection and try again.")
        )
        self.dialogRetryButton.setStyleSheet(
            _translate(
                "AtlasPressShippingDialog",
                "QPushButton { background: #3a7ebf; color: white; border: none;\n"
                "              border-radius: 4px; padding: 6px 24px; font-size: 12px; }\n"
                "            QPushButton:hover { background: #2e6aaa; }",
            )
        )
        self.dialogRetryButton.setText(_translate("AtlasPressShippingDialog", "Retry"))
