# Form implementation generated from reading ui file 'ui/product/product_selection.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_AtlasPressProductSelectionDialog(object):
    def setupUi(self, AtlasPressProductSelectionDialog):
        AtlasPressProductSelectionDialog.setObjectName("AtlasPressProductSelectionDialog")
        AtlasPressProductSelectionDialog.resize(760, 580)
        AtlasPressProductSelectionDialog.setMinimumSize(QtCore.QSize(700, 540))
        self.rootLayout = QtWidgets.QVBoxLayout(AtlasPressProductSelectionDialog)
        self.rootLayout.setContentsMargins(20, 18, 20, 16)
        self.rootLayout.setSpacing(14)
        self.rootLayout.setObjectName("rootLayout")
        self.headerLabel = QtWidgets.QLabel(parent=AtlasPressProductSelectionDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerLabel.sizePolicy().hasHeightForWidth())
        self.headerLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.headerLabel.setFont(font)
        self.headerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headerLabel.setObjectName("headerLabel")
        self.rootLayout.addWidget(self.headerLabel)
        self.stepIndicatorLabel = QtWidgets.QLabel(parent=AtlasPressProductSelectionDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepIndicatorLabel.sizePolicy().hasHeightForWidth())
        self.stepIndicatorLabel.setSizePolicy(sizePolicy)
        self.stepIndicatorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.stepIndicatorLabel.setObjectName("stepIndicatorLabel")
        self.rootLayout.addWidget(self.stepIndicatorLabel)
        self.dividerLine = QtWidgets.QFrame(parent=AtlasPressProductSelectionDialog)
        self.dividerLine.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.dividerLine.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.dividerLine.setObjectName("dividerLine")
        self.rootLayout.addWidget(self.dividerLine)
        self.startupLoadingPage = QtWidgets.QWidget(parent=AtlasPressProductSelectionDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.startupLoadingPage.sizePolicy().hasHeightForWidth())
        self.startupLoadingPage.setSizePolicy(sizePolicy)
        self.startupLoadingPage.setObjectName("startupLoadingPage")
        self.startupLoadingLayout = QtWidgets.QVBoxLayout(self.startupLoadingPage)
        self.startupLoadingLayout.setObjectName("startupLoadingLayout")
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.startupLoadingLayout.addItem(spacerItem)
        self.startupSpinnerLabel = QtWidgets.QLabel(parent=self.startupLoadingPage)
        self.startupSpinnerLabel.setMinimumSize(QtCore.QSize(0, 40))
        self.startupSpinnerLabel.setText("")
        self.startupSpinnerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.startupSpinnerLabel.setObjectName("startupSpinnerLabel")
        self.startupLoadingLayout.addWidget(self.startupSpinnerLabel)
        self.startupLoadingTextLabel = QtWidgets.QLabel(parent=self.startupLoadingPage)
        self.startupLoadingTextLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.startupLoadingTextLabel.setWordWrap(True)
        self.startupLoadingTextLabel.setObjectName("startupLoadingTextLabel")
        self.startupLoadingLayout.addWidget(self.startupLoadingTextLabel)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.startupLoadingLayout.addItem(spacerItem1)
        self.rootLayout.addWidget(self.startupLoadingPage)
        self.mainSplitter = QtWidgets.QSplitter(parent=AtlasPressProductSelectionDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.mainSplitter.sizePolicy().hasHeightForWidth())
        self.mainSplitter.setSizePolicy(sizePolicy)
        self.mainSplitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.mainSplitter.setChildrenCollapsible(False)
        self.mainSplitter.setObjectName("mainSplitter")
        self.previewGroupBox = QtWidgets.QGroupBox(parent=self.mainSplitter)
        self.previewGroupBox.setMinimumSize(QtCore.QSize(360, 0))
        self.previewGroupBox.setObjectName("previewGroupBox")
        self.previewPaneLayout = QtWidgets.QVBoxLayout(self.previewGroupBox)
        self.previewPaneLayout.setObjectName("previewPaneLayout")
        self.previewStackedWidget = QtWidgets.QStackedWidget(parent=self.previewGroupBox)
        self.previewStackedWidget.setObjectName("previewStackedWidget")
        self.previewEmptyPage = QtWidgets.QWidget()
        self.previewEmptyPage.setObjectName("previewEmptyPage")
        self.previewEmptyLayout = QtWidgets.QVBoxLayout(self.previewEmptyPage)
        self.previewEmptyLayout.setObjectName("previewEmptyLayout")
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.previewEmptyLayout.addItem(spacerItem2)
        self.previewEmptyTextLabel = QtWidgets.QLabel(parent=self.previewEmptyPage)
        self.previewEmptyTextLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.previewEmptyTextLabel.setWordWrap(True)
        self.previewEmptyTextLabel.setObjectName("previewEmptyTextLabel")
        self.previewEmptyLayout.addWidget(self.previewEmptyTextLabel)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.previewEmptyLayout.addItem(spacerItem3)
        self.previewStackedWidget.addWidget(self.previewEmptyPage)
        self.previewLoadingPage = QtWidgets.QWidget()
        self.previewLoadingPage.setObjectName("previewLoadingPage")
        self.previewLoadingLayout = QtWidgets.QVBoxLayout(self.previewLoadingPage)
        self.previewLoadingLayout.setObjectName("previewLoadingLayout")
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.previewLoadingLayout.addItem(spacerItem4)
        self.previewLoadingSpinnerLabel = QtWidgets.QLabel(parent=self.previewLoadingPage)
        self.previewLoadingSpinnerLabel.setMinimumSize(QtCore.QSize(0, 40))
        self.previewLoadingSpinnerLabel.setText("")
        self.previewLoadingSpinnerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.previewLoadingSpinnerLabel.setObjectName("previewLoadingSpinnerLabel")
        self.previewLoadingLayout.addWidget(self.previewLoadingSpinnerLabel)
        self.previewLoadingTextLabel = QtWidgets.QLabel(parent=self.previewLoadingPage)
        self.previewLoadingTextLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.previewLoadingTextLabel.setWordWrap(True)
        self.previewLoadingTextLabel.setObjectName("previewLoadingTextLabel")
        self.previewLoadingLayout.addWidget(self.previewLoadingTextLabel)
        spacerItem5 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.previewLoadingLayout.addItem(spacerItem5)
        self.previewStackedWidget.addWidget(self.previewLoadingPage)
        self.previewContentPage = QtWidgets.QWidget()
        self.previewContentPage.setObjectName("previewContentPage")
        self.previewContentLayout = QtWidgets.QVBoxLayout(self.previewContentPage)
        self.previewContentLayout.setContentsMargins(0, 0, 0, 0)
        self.previewContentLayout.setSpacing(6)
        self.previewContentLayout.setObjectName("previewContentLayout")
        self.previewGraphicsView = QtWidgets.QGraphicsView(parent=self.previewContentPage)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.previewGraphicsView.sizePolicy().hasHeightForWidth())
        self.previewGraphicsView.setSizePolicy(sizePolicy)
        self.previewGraphicsView.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.previewGraphicsView.setObjectName("previewGraphicsView")
        self.previewContentLayout.addWidget(self.previewGraphicsView)
        self.previewZoomLayout = QtWidgets.QHBoxLayout()
        self.previewZoomLayout.setObjectName("previewZoomLayout")
        spacerItem6 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.previewZoomLayout.addItem(spacerItem6)
        self.zoomOutButton = QtWidgets.QToolButton(parent=self.previewContentPage)
        self.zoomOutButton.setAutoRaise(True)
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.previewZoomLayout.addWidget(self.zoomOutButton)
        self.zoomFitButton = QtWidgets.QToolButton(parent=self.previewContentPage)
        self.zoomFitButton.setAutoRaise(True)
        self.zoomFitButton.setObjectName("zoomFitButton")
        self.previewZoomLayout.addWidget(self.zoomFitButton)
        self.zoomInButton = QtWidgets.QToolButton(parent=self.previewContentPage)
        self.zoomInButton.setAutoRaise(True)
        self.zoomInButton.setObjectName("zoomInButton")
        self.previewZoomLayout.addWidget(self.zoomInButton)
        spacerItem7 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.previewZoomLayout.addItem(spacerItem7)
        self.previewContentLayout.addLayout(self.previewZoomLayout)
        self.previewInteractionLabel = QtWidgets.QLabel(parent=self.previewContentPage)
        self.previewInteractionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.previewInteractionLabel.setWordWrap(True)
        self.previewInteractionLabel.setObjectName("previewInteractionLabel")
        self.previewContentLayout.addWidget(self.previewInteractionLabel)
        self.previewStackedWidget.addWidget(self.previewContentPage)
        self.previewErrorPage = QtWidgets.QWidget()
        self.previewErrorPage.setObjectName("previewErrorPage")
        self.previewErrorLayout = QtWidgets.QVBoxLayout(self.previewErrorPage)
        self.previewErrorLayout.setObjectName("previewErrorLayout")
        spacerItem8 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.previewErrorLayout.addItem(spacerItem8)
        self.previewErrorTitleLabel = QtWidgets.QLabel(parent=self.previewErrorPage)
        font = QtGui.QFont()
        font.setBold(True)
        self.previewErrorTitleLabel.setFont(font)
        self.previewErrorTitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.previewErrorTitleLabel.setObjectName("previewErrorTitleLabel")
        self.previewErrorLayout.addWidget(self.previewErrorTitleLabel)
        self.previewErrorTextLabel = QtWidgets.QLabel(parent=self.previewErrorPage)
        self.previewErrorTextLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.previewErrorTextLabel.setWordWrap(True)
        self.previewErrorTextLabel.setObjectName("previewErrorTextLabel")
        self.previewErrorLayout.addWidget(self.previewErrorTextLabel)
        self.previewRetryLayout = QtWidgets.QHBoxLayout()
        self.previewRetryLayout.setObjectName("previewRetryLayout")
        spacerItem9 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.previewRetryLayout.addItem(spacerItem9)
        self.previewRetryButton = QtWidgets.QPushButton(parent=self.previewErrorPage)
        self.previewRetryButton.setObjectName("previewRetryButton")
        self.previewRetryLayout.addWidget(self.previewRetryButton)
        spacerItem10 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.previewRetryLayout.addItem(spacerItem10)
        self.previewErrorLayout.addLayout(self.previewRetryLayout)
        spacerItem11 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.previewErrorLayout.addItem(spacerItem11)
        self.previewStackedWidget.addWidget(self.previewErrorPage)
        self.previewPaneLayout.addWidget(self.previewStackedWidget)
        self.previewNoteLabel = QtWidgets.QLabel(parent=self.previewGroupBox)
        self.previewNoteLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.previewNoteLabel.setWordWrap(True)
        self.previewNoteLabel.setObjectName("previewNoteLabel")
        self.previewPaneLayout.addWidget(self.previewNoteLabel)
        self.productConfigurationScrollArea = QtWidgets.QScrollArea(parent=self.mainSplitter)
        self.productConfigurationScrollArea.setMinimumSize(QtCore.QSize(270, 0))
        self.productConfigurationScrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.productConfigurationScrollArea.setWidgetResizable(True)
        self.productConfigurationScrollArea.setObjectName("productConfigurationScrollArea")
        self.productConfigurationPane = QtWidgets.QWidget()
        self.productConfigurationPane.setGeometry(QtCore.QRect(0, 0, 310, 430))
        self.productConfigurationPane.setObjectName("productConfigurationPane")
        self.productConfigurationPaneLayout = QtWidgets.QVBoxLayout(self.productConfigurationPane)
        self.productConfigurationPaneLayout.setContentsMargins(4, 0, 4, 4)
        self.productConfigurationPaneLayout.setSpacing(12)
        self.productConfigurationPaneLayout.setObjectName("productConfigurationPaneLayout")
        self.productSection = QtWidgets.QWidget(parent=self.productConfigurationPane)
        self.productSection.setObjectName("productSection")
        self.productFieldLayout = QtWidgets.QVBoxLayout(self.productSection)
        self.productFieldLayout.setContentsMargins(0, 0, 0, 0)
        self.productFieldLayout.setObjectName("productFieldLayout")
        self.productLabel = QtWidgets.QLabel(parent=self.productSection)
        font = QtGui.QFont()
        font.setBold(True)
        self.productLabel.setFont(font)
        self.productLabel.setObjectName("productLabel")
        self.productFieldLayout.addWidget(self.productLabel)
        self.productComboBox = QtWidgets.QComboBox(parent=self.productSection)
        self.productComboBox.setObjectName("productComboBox")
        self.productComboBox.addItem("")
        self.productComboBox.addItem("")
        self.productFieldLayout.addWidget(self.productComboBox)
        self.productLoadingStatusLabel = QtWidgets.QLabel(parent=self.productSection)
        self.productLoadingStatusLabel.setWordWrap(True)
        self.productLoadingStatusLabel.setObjectName("productLoadingStatusLabel")
        self.productFieldLayout.addWidget(self.productLoadingStatusLabel)
        self.productLoadingRetryButton = QtWidgets.QPushButton(parent=self.productSection)
        self.productLoadingRetryButton.setObjectName("productLoadingRetryButton")
        self.productFieldLayout.addWidget(self.productLoadingRetryButton)
        self.productConfigurationPaneLayout.addWidget(self.productSection)
        self.sizeSection = QtWidgets.QWidget(parent=self.productConfigurationPane)
        self.sizeSection.setObjectName("sizeSection")
        self.sizeFieldLayout = QtWidgets.QVBoxLayout(self.sizeSection)
        self.sizeFieldLayout.setContentsMargins(0, 0, 0, 0)
        self.sizeFieldLayout.setObjectName("sizeFieldLayout")
        self.sizeLabel = QtWidgets.QLabel(parent=self.sizeSection)
        font = QtGui.QFont()
        font.setBold(True)
        self.sizeLabel.setFont(font)
        self.sizeLabel.setObjectName("sizeLabel")
        self.sizeFieldLayout.addWidget(self.sizeLabel)
        self.sizeComboBox = QtWidgets.QComboBox(parent=self.sizeSection)
        self.sizeComboBox.setObjectName("sizeComboBox")
        self.sizeComboBox.addItem("")
        self.sizeFieldLayout.addWidget(self.sizeComboBox)
        self.productConfigurationPaneLayout.addWidget(self.sizeSection)
        self.mapUploadGroupBox = QtWidgets.QGroupBox(parent=self.productConfigurationPane)
        self.mapUploadGroupBox.setObjectName("mapUploadGroupBox")
        self.mapUploadStatusLayout = QtWidgets.QVBoxLayout(self.mapUploadGroupBox)
        self.mapUploadStatusLayout.setObjectName("mapUploadStatusLayout")
        self.mapUploadStatusLabel = QtWidgets.QLabel(parent=self.mapUploadGroupBox)
        self.mapUploadStatusLabel.setWordWrap(True)
        self.mapUploadStatusLabel.setObjectName("mapUploadStatusLabel")
        self.mapUploadStatusLayout.addWidget(self.mapUploadStatusLabel)
        self.mapUploadRetryButton = QtWidgets.QPushButton(parent=self.mapUploadGroupBox)
        self.mapUploadRetryButton.setObjectName("mapUploadRetryButton")
        self.mapUploadStatusLayout.addWidget(self.mapUploadRetryButton)
        self.productConfigurationPaneLayout.addWidget(self.mapUploadGroupBox)
        spacerItem12 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.productConfigurationPaneLayout.addItem(spacerItem12)
        self.productPriceLayout = QtWidgets.QHBoxLayout()
        self.productPriceLayout.setObjectName("productPriceLayout")
        self.productPriceTitleLabel = QtWidgets.QLabel(parent=self.productConfigurationPane)
        self.productPriceTitleLabel.setObjectName("productPriceTitleLabel")
        self.productPriceLayout.addWidget(self.productPriceTitleLabel)
        spacerItem13 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.productPriceLayout.addItem(spacerItem13)
        self.productPriceValueLabel = QtWidgets.QLabel(parent=self.productConfigurationPane)
        font = QtGui.QFont()
        font.setBold(True)
        self.productPriceValueLabel.setFont(font)
        self.productPriceValueLabel.setObjectName("productPriceValueLabel")
        self.productPriceLayout.addWidget(self.productPriceValueLabel)
        self.productConfigurationPaneLayout.addLayout(self.productPriceLayout)
        self.basePriceNoteLabel = QtWidgets.QLabel(parent=self.productConfigurationPane)
        self.basePriceNoteLabel.setWordWrap(True)
        self.basePriceNoteLabel.setObjectName("basePriceNoteLabel")
        self.productConfigurationPaneLayout.addWidget(self.basePriceNoteLabel)
        self.productConfigurationScrollArea.setWidget(self.productConfigurationPane)
        self.rootLayout.addWidget(self.mainSplitter)
        self.actionButtonBox = QtWidgets.QDialogButtonBox(parent=AtlasPressProductSelectionDialog)
        self.actionButtonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.actionButtonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.actionButtonBox.setObjectName("actionButtonBox")
        self.rootLayout.addWidget(self.actionButtonBox)

        self.retranslateUi(AtlasPressProductSelectionDialog)
        self.previewStackedWidget.setCurrentIndex(0)
        self.actionButtonBox.accepted.connect(AtlasPressProductSelectionDialog.accept)  # type: ignore
        self.actionButtonBox.rejected.connect(AtlasPressProductSelectionDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AtlasPressProductSelectionDialog)

    def retranslateUi(self, AtlasPressProductSelectionDialog):
        _translate = QtCore.QCoreApplication.translate
        AtlasPressProductSelectionDialog.setWindowTitle(
            _translate("AtlasPressProductSelectionDialog", "Atlas Press — Choose Product")
        )
        self.headerLabel.setText(
            _translate("AtlasPressProductSelectionDialog", "🗺️  Print & Order Your Map")
        )
        self.stepIndicatorLabel.setText(
            _translate("AtlasPressProductSelectionDialog", "Step 1 of 4 — Choose Product")
        )
        self.stepIndicatorLabel.setStyleSheet(
            _translate("AtlasPressProductSelectionDialog", "color: palette(text); font-size: 11px;")
        )
        self.startupLoadingTextLabel.setText(
            _translate("AtlasPressProductSelectionDialog", "Preparing your order…")
        )
        self.previewGroupBox.setTitle(_translate("AtlasPressProductSelectionDialog", "Preview"))
        self.previewEmptyTextLabel.setText(
            _translate(
                "AtlasPressProductSelectionDialog",
                "Select a product and size to generate a preview.",
            )
        )
        self.previewLoadingTextLabel.setText(
            _translate("AtlasPressProductSelectionDialog", "Generating your preview…")
        )
        self.previewGraphicsView.setToolTip(
            _translate(
                "AtlasPressProductSelectionDialog", "Use the mouse wheel to zoom and drag to pan."
            )
        )
        self.zoomOutButton.setText(_translate("AtlasPressProductSelectionDialog", "−"))
        self.zoomOutButton.setToolTip(_translate("AtlasPressProductSelectionDialog", "Zoom out"))
        self.zoomFitButton.setText(_translate("AtlasPressProductSelectionDialog", "Fit"))
        self.zoomFitButton.setToolTip(
            _translate("AtlasPressProductSelectionDialog", "Fit preview to window")
        )
        self.zoomInButton.setText(_translate("AtlasPressProductSelectionDialog", "+"))
        self.zoomInButton.setToolTip(_translate("AtlasPressProductSelectionDialog", "Zoom in"))
        self.previewInteractionLabel.setText(
            _translate(
                "AtlasPressProductSelectionDialog",
                "Use the mouse wheel or double-click to zoom. Drag to pan.",
            )
        )
        self.previewErrorTitleLabel.setText(
            _translate("AtlasPressProductSelectionDialog", "Preview unavailable")
        )
        self.previewErrorTextLabel.setText(
            _translate("AtlasPressProductSelectionDialog", "Could not generate a preview.")
        )
        self.previewRetryButton.setText(
            _translate("AtlasPressProductSelectionDialog", "Retry Preview")
        )
        self.previewNoteLabel.setText(
            _translate(
                "AtlasPressProductSelectionDialog",
                "Product preview only. The final printed product may vary slightly.",
            )
        )
        self.productLabel.setText(_translate("AtlasPressProductSelectionDialog", "Product"))
        self.productComboBox.setItemText(
            0, _translate("AtlasPressProductSelectionDialog", "Canvas Print")
        )
        self.productComboBox.setItemText(
            1, _translate("AtlasPressProductSelectionDialog", "Poster Print")
        )
        self.productLoadingStatusLabel.setText(
            _translate("AtlasPressProductSelectionDialog", "Loading available sizes…")
        )
        self.productLoadingRetryButton.setText(
            _translate("AtlasPressProductSelectionDialog", "Retry Loading Products")
        )
        self.sizeLabel.setText(_translate("AtlasPressProductSelectionDialog", "Size"))
        self.sizeComboBox.setItemText(
            0, _translate("AtlasPressProductSelectionDialog", "Select a size")
        )
        self.mapUploadGroupBox.setTitle(_translate("AtlasPressProductSelectionDialog", "Map"))
        self.mapUploadStatusLabel.setText(
            _translate("AtlasPressProductSelectionDialog", "Preparing map…")
        )
        self.mapUploadRetryButton.setText(
            _translate("AtlasPressProductSelectionDialog", "Retry Map Upload")
        )
        self.productPriceTitleLabel.setText(
            _translate("AtlasPressProductSelectionDialog", "Product price")
        )
        self.productPriceValueLabel.setText(_translate("AtlasPressProductSelectionDialog", "—"))
        self.basePriceNoteLabel.setText(
            _translate(
                "AtlasPressProductSelectionDialog",
                "ℹ️  Prices are base prices and exclude shipping & tax.",
            )
        )
