# Form implementation generated from reading ui file 'ui/product/product_selection.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_AtlasPressProductDialog(object):
    def setupUi(self, AtlasPressProductDialog):
        AtlasPressProductDialog.setObjectName("AtlasPressProductDialog")
        AtlasPressProductDialog.resize(594, 500)
        AtlasPressProductDialog.setMinimumSize(QtCore.QSize(580, 480))
        self.rootLayout = QtWidgets.QVBoxLayout(AtlasPressProductDialog)
        self.rootLayout.setContentsMargins(20, 18, 20, 16)
        self.rootLayout.setSpacing(14)
        self.rootLayout.setObjectName("rootLayout")
        self.headerLabel = QtWidgets.QLabel(parent=AtlasPressProductDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.headerLabel.setFont(font)
        self.headerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headerLabel.setObjectName("headerLabel")
        self.rootLayout.addWidget(self.headerLabel)
        self.subtitleLabel = QtWidgets.QLabel(parent=AtlasPressProductDialog)
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.rootLayout.addWidget(self.subtitleLabel)
        self.dividerLine = QtWidgets.QFrame(parent=AtlasPressProductDialog)
        self.dividerLine.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.dividerLine.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.dividerLine.setObjectName("dividerLine")
        self.rootLayout.addWidget(self.dividerLine)
        self.productTypeGroupBox = QtWidgets.QGroupBox(parent=AtlasPressProductDialog)
        self.productTypeGroupBox.setObjectName("productTypeGroupBox")
        self.productGroupLayout = QtWidgets.QVBoxLayout(self.productTypeGroupBox)
        self.productGroupLayout.setSpacing(6)
        self.productGroupLayout.setObjectName("productGroupLayout")
        self.radioLayout = QtWidgets.QHBoxLayout()
        self.radioLayout.setSpacing(20)
        self.radioLayout.setObjectName("radioLayout")
        self.radioCanvas = QtWidgets.QRadioButton(parent=self.productTypeGroupBox)
        self.radioCanvas.setChecked(True)
        self.radioCanvas.setObjectName("radioCanvas")
        self.radioLayout.addWidget(self.radioCanvas)
        self.radioPoster = QtWidgets.QRadioButton(parent=self.productTypeGroupBox)
        self.radioPoster.setObjectName("radioPoster")
        self.radioLayout.addWidget(self.radioPoster)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.radioLayout.addItem(spacerItem)
        self.productGroupLayout.addLayout(self.radioLayout)
        self.descriptionLabel = QtWidgets.QLabel(parent=self.productTypeGroupBox)
        self.descriptionLabel.setWordWrap(True)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.productGroupLayout.addWidget(self.descriptionLabel)
        self.rootLayout.addWidget(self.productTypeGroupBox)
        self.sizeGroupBox = QtWidgets.QGroupBox(parent=AtlasPressProductDialog)
        self.sizeGroupBox.setObjectName("sizeGroupBox")
        self.sizeGroupLayout = QtWidgets.QVBoxLayout(self.sizeGroupBox)
        self.sizeGroupLayout.setSpacing(10)
        self.sizeGroupLayout.setObjectName("sizeGroupLayout")
        self.sizeStackedWidget = QtWidgets.QStackedWidget(parent=self.sizeGroupBox)
        self.sizeStackedWidget.setObjectName("sizeStackedWidget")
        self.sizeLoadingPage = QtWidgets.QWidget()
        self.sizeLoadingPage.setObjectName("sizeLoadingPage")
        self.loadingPageLayout = QtWidgets.QVBoxLayout(self.sizeLoadingPage)
        self.loadingPageLayout.setContentsMargins(-1, 12, -1, 12)
        self.loadingPageLayout.setSpacing(8)
        self.loadingPageLayout.setObjectName("loadingPageLayout")
        self.loadingTextLabel = QtWidgets.QLabel(parent=self.sizeLoadingPage)
        self.loadingTextLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loadingTextLabel.setObjectName("loadingTextLabel")
        self.loadingPageLayout.addWidget(self.loadingTextLabel)
        self.sizeStackedWidget.addWidget(self.sizeLoadingPage)
        self.sizeCardsPage = QtWidgets.QWidget()
        self.sizeCardsPage.setObjectName("sizeCardsPage")
        self.cardsPageLayout = QtWidgets.QVBoxLayout(self.sizeCardsPage)
        self.cardsPageLayout.setContentsMargins(0, 4, 0, 4)
        self.cardsPageLayout.setSpacing(8)
        self.cardsPageLayout.setObjectName("cardsPageLayout")
        self.sizeCardsLayout = QtWidgets.QHBoxLayout()
        self.sizeCardsLayout.setSpacing(10)
        self.sizeCardsLayout.setObjectName("sizeCardsLayout")
        self.cardsPageLayout.addLayout(self.sizeCardsLayout)
        self.selectionSizeLabel = QtWidgets.QLabel(parent=self.sizeCardsPage)
        self.selectionSizeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.selectionSizeLabel.setObjectName("selectionSizeLabel")
        self.cardsPageLayout.addWidget(self.selectionSizeLabel)
        self.sizeStackedWidget.addWidget(self.sizeCardsPage)
        self.sizeErrorPage = QtWidgets.QWidget()
        self.sizeErrorPage.setObjectName("sizeErrorPage")
        self.errorPageLayout = QtWidgets.QVBoxLayout(self.sizeErrorPage)
        self.errorPageLayout.setContentsMargins(-1, 10, -1, 10)
        self.errorPageLayout.setSpacing(6)
        self.errorPageLayout.setObjectName("errorPageLayout")
        self.errorIconLabel = QtWidgets.QLabel(parent=self.sizeErrorPage)
        self.errorIconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.errorIconLabel.setObjectName("errorIconLabel")
        self.errorPageLayout.addWidget(self.errorIconLabel)
        self.errorMessageLabel = QtWidgets.QLabel(parent=self.sizeErrorPage)
        self.errorMessageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.errorMessageLabel.setWordWrap(True)
        self.errorMessageLabel.setObjectName("errorMessageLabel")
        self.errorPageLayout.addWidget(self.errorMessageLabel)
        self.retryButtonLayout = QtWidgets.QHBoxLayout()
        self.retryButtonLayout.setObjectName("retryButtonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.retryButtonLayout.addItem(spacerItem1)
        self.retryButton = QtWidgets.QPushButton(parent=self.sizeErrorPage)
        self.retryButton.setObjectName("retryButton")
        self.retryButtonLayout.addWidget(self.retryButton)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.retryButtonLayout.addItem(spacerItem2)
        self.errorPageLayout.addLayout(self.retryButtonLayout)
        self.sizeStackedWidget.addWidget(self.sizeErrorPage)
        self.sizeGroupLayout.addWidget(self.sizeStackedWidget)
        self.rootLayout.addWidget(self.sizeGroupBox)
        self.priceNoteLabel = QtWidgets.QLabel(parent=AtlasPressProductDialog)
        self.priceNoteLabel.setWordWrap(True)
        self.priceNoteLabel.setObjectName("priceNoteLabel")
        self.rootLayout.addWidget(self.priceNoteLabel)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.rootLayout.addItem(spacerItem3)
        self.buttonsActions = QtWidgets.QDialogButtonBox(parent=AtlasPressProductDialog)
        self.buttonsActions.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonsActions.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.buttonsActions.setObjectName("buttonsActions")
        self.rootLayout.addWidget(self.buttonsActions)

        self.retranslateUi(AtlasPressProductDialog)
        self.sizeStackedWidget.setCurrentIndex(0)
        self.buttonsActions.accepted.connect(AtlasPressProductDialog.accept)  # type: ignore
        self.buttonsActions.rejected.connect(AtlasPressProductDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AtlasPressProductDialog)

    def retranslateUi(self, AtlasPressProductDialog):
        _translate = QtCore.QCoreApplication.translate
        AtlasPressProductDialog.setWindowTitle(
            _translate("AtlasPressProductDialog", "Atlas Press — Choose Product")
        )
        self.headerLabel.setText(_translate("AtlasPressProductDialog", "🗺️ Print & Order Your Map"))
        self.subtitleLabel.setStyleSheet(
            _translate("AtlasPressProductDialog", "color: #666666; font-size: 11px;")
        )
        self.subtitleLabel.setText(
            _translate("AtlasPressProductDialog", "Select a product type, then pick a size.")
        )
        self.dividerLine.setStyleSheet(_translate("AtlasPressProductDialog", "color: #dddddd;"))
        self.productTypeGroupBox.setStyleSheet(
            _translate("AtlasPressProductDialog", "QGroupBox { font-weight: bold; }")
        )
        self.productTypeGroupBox.setTitle(_translate("AtlasPressProductDialog", "Product Type"))
        self.radioCanvas.setText(_translate("AtlasPressProductDialog", "Canvas Print"))
        self.radioPoster.setText(_translate("AtlasPressProductDialog", "Poster Print"))
        self.descriptionLabel.setStyleSheet(
            _translate("AtlasPressProductDialog", "color: #555555; font-size: 11px;")
        )
        self.descriptionLabel.setText(
            _translate("AtlasPressProductDialog", "Premium gallery-wrapped canvas, ready to hang.")
        )
        self.sizeGroupBox.setStyleSheet(
            _translate("AtlasPressProductDialog", "QGroupBox { font-weight: bold; }")
        )
        self.sizeGroupBox.setTitle(_translate("AtlasPressProductDialog", "Size"))
        self.loadingTextLabel.setStyleSheet(
            _translate("AtlasPressProductDialog", "color: #888888; font-size: 11px;")
        )
        self.loadingTextLabel.setText(_translate("AtlasPressProductDialog", "Fetching products…"))
        self.selectionSizeLabel.setStyleSheet(
            _translate(
                "AtlasPressProductDialog",
                "color: #3a7ebf; font-weight: bold; font-size: 12px; margin-top:\n"
                "                            2px;",
            )
        )
        self.selectionSizeLabel.setText(_translate("AtlasPressProductDialog", "No size selected"))
        self.errorIconLabel.setStyleSheet(_translate("AtlasPressProductDialog", "font-size: 22px;"))
        self.errorIconLabel.setText(_translate("AtlasPressProductDialog", "⚠️"))
        self.errorMessageLabel.setStyleSheet(
            _translate("AtlasPressProductDialog", "color: #cc4444; font-size: 11px;")
        )
        self.errorMessageLabel.setText(
            _translate(
                "AtlasPressProductDialog", "Could not load products. Please check your connection."
            )
        )
        self.retryButton.setStyleSheet(
            _translate(
                "AtlasPressProductDialog",
                "\n"
                "                                QPushButton {\n"
                "                                background: #3a7ebf;\n"
                "                                color: white;\n"
                "                                border: none;\n"
                "                                border-radius: 4px;\n"
                "                                padding: 4px 16px;\n"
                "                                font-size: 11px;\n"
                "                                }\n"
                "                                QPushButton:hover { background: #2e6aaa; }\n"
                "                              ",
            )
        )
        self.retryButton.setText(_translate("AtlasPressProductDialog", "Retry"))
        self.priceNoteLabel.setStyleSheet(
            _translate("AtlasPressProductDialog", "color: #999999; font-size: 10px;")
        )
        self.priceNoteLabel.setText(
            _translate(
                "AtlasPressProductDialog", "ℹ️ Prices are base prices and exclude shipping & tax."
            )
        )
