# Form implementation generated from reading ui file 'ui/quote/quote_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_AtlasPressQuoteDialog(object):
    def setupUi(self, AtlasPressQuoteDialog):
        AtlasPressQuoteDialog.setObjectName("AtlasPressQuoteDialog")
        AtlasPressQuoteDialog.resize(700, 680)
        AtlasPressQuoteDialog.setMinimumSize(QtCore.QSize(680, 640))
        self.rootLayout = QtWidgets.QVBoxLayout(AtlasPressQuoteDialog)
        self.rootLayout.setContentsMargins(20, 18, 20, 16)
        self.rootLayout.setSpacing(14)
        self.rootLayout.setObjectName("rootLayout")
        self.headerLabel = QtWidgets.QLabel(parent=AtlasPressQuoteDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.headerLabel.setFont(font)
        self.headerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headerLabel.setObjectName("headerLabel")
        self.rootLayout.addWidget(self.headerLabel)
        self.stepIndicatorLabel = QtWidgets.QLabel(parent=AtlasPressQuoteDialog)
        self.stepIndicatorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.stepIndicatorLabel.setObjectName("stepIndicatorLabel")
        self.rootLayout.addWidget(self.stepIndicatorLabel)
        self.dividerLine = QtWidgets.QFrame(parent=AtlasPressQuoteDialog)
        self.dividerLine.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.dividerLine.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.dividerLine.setObjectName("dividerLine")
        self.rootLayout.addWidget(self.dividerLine)
        self.dialogStackedWidget = QtWidgets.QStackedWidget(parent=AtlasPressQuoteDialog)
        self.dialogStackedWidget.setObjectName("dialogStackedWidget")
        self.quoteLoadingPage = QtWidgets.QWidget()
        self.quoteLoadingPage.setObjectName("quoteLoadingPage")
        self.quoteLoadingLayout = QtWidgets.QVBoxLayout(self.quoteLoadingPage)
        self.quoteLoadingLayout.setSpacing(12)
        self.quoteLoadingLayout.setObjectName("quoteLoadingLayout")
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.quoteLoadingLayout.addItem(spacerItem)
        self.quoteLoadingSpinnerLabel = QtWidgets.QLabel(parent=self.quoteLoadingPage)
        self.quoteLoadingSpinnerLabel.setText("")
        self.quoteLoadingSpinnerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.quoteLoadingSpinnerLabel.setMinimumSize(QtCore.QSize(0, 36))
        self.quoteLoadingSpinnerLabel.setObjectName("quoteLoadingSpinnerLabel")
        self.quoteLoadingLayout.addWidget(self.quoteLoadingSpinnerLabel)
        self.quoteLoadingTextLabel = QtWidgets.QLabel(parent=self.quoteLoadingPage)
        self.quoteLoadingTextLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.quoteLoadingTextLabel.setObjectName("quoteLoadingTextLabel")
        self.quoteLoadingLayout.addWidget(self.quoteLoadingTextLabel)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.quoteLoadingLayout.addItem(spacerItem1)
        self.dialogStackedWidget.addWidget(self.quoteLoadingPage)
        self.quoteContentPage = QtWidgets.QWidget()
        self.quoteContentPage.setObjectName("quoteContentPage")
        self.quoteContentLayout = QtWidgets.QVBoxLayout(self.quoteContentPage)
        self.quoteContentLayout.setContentsMargins(0, 0, 0, 0)
        self.quoteContentLayout.setSpacing(14)
        self.quoteContentLayout.setObjectName("quoteContentLayout")
        self.productSummaryGroupBox = QtWidgets.QGroupBox(parent=self.quoteContentPage)
        self.productSummaryGroupBox.setObjectName("productSummaryGroupBox")
        self.productSummaryLayout = QtWidgets.QHBoxLayout(self.productSummaryGroupBox)
        self.productSummaryLayout.setSpacing(10)
        self.productSummaryLayout.setObjectName("productSummaryLayout")
        self.productThumbnailLabel = QtWidgets.QLabel(parent=self.productSummaryGroupBox)
        self.productThumbnailLabel.setMinimumSize(QtCore.QSize(56, 56))
        self.productThumbnailLabel.setMaximumSize(QtCore.QSize(56, 56))
        self.productThumbnailLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.productThumbnailLabel.setText("")
        self.productThumbnailLabel.setObjectName("productThumbnailLabel")
        self.productSummaryLayout.addWidget(self.productThumbnailLabel)
        self.productSummaryTextLayout = QtWidgets.QVBoxLayout()
        self.productSummaryTextLayout.setSpacing(3)
        self.productSummaryTextLayout.setObjectName("productSummaryTextLayout")
        self.productNameLabel = QtWidgets.QLabel(parent=self.productSummaryGroupBox)
        self.productNameLabel.setObjectName("productNameLabel")
        self.productSummaryTextLayout.addWidget(self.productNameLabel)
        self.productVariantLabel = QtWidgets.QLabel(parent=self.productSummaryGroupBox)
        self.productVariantLabel.setWordWrap(True)
        self.productVariantLabel.setObjectName("productVariantLabel")
        self.productSummaryTextLayout.addWidget(self.productVariantLabel)
        self.productSummaryLayout.addLayout(self.productSummaryTextLayout)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.productSummaryLayout.addItem(spacerItem2)
        self.quoteContentLayout.addWidget(self.productSummaryGroupBox)
        self.shippingAddressGroupBox = QtWidgets.QGroupBox(parent=self.quoteContentPage)
        self.shippingAddressGroupBox.setObjectName("shippingAddressGroupBox")
        self.shippingAddressLayout = QtWidgets.QVBoxLayout(self.shippingAddressGroupBox)
        self.shippingAddressLayout.setSpacing(3)
        self.shippingAddressLayout.setObjectName("shippingAddressLayout")
        self.shipNameLabel = QtWidgets.QLabel(parent=self.shippingAddressGroupBox)
        self.shipNameLabel.setWordWrap(True)
        self.shipNameLabel.setObjectName("shipNameLabel")
        self.shippingAddressLayout.addWidget(self.shipNameLabel)
        self.shipEmailLabel = QtWidgets.QLabel(parent=self.shippingAddressGroupBox)
        self.shipEmailLabel.setWordWrap(True)
        self.shipEmailLabel.setObjectName("shipEmailLabel")
        self.shippingAddressLayout.addWidget(self.shipEmailLabel)
        self.shipAddressLabel = QtWidgets.QLabel(parent=self.shippingAddressGroupBox)
        self.shipAddressLabel.setWordWrap(True)
        self.shipAddressLabel.setObjectName("shipAddressLabel")
        self.shippingAddressLayout.addWidget(self.shipAddressLabel)
        self.shipCityLabel = QtWidgets.QLabel(parent=self.shippingAddressGroupBox)
        self.shipCityLabel.setWordWrap(True)
        self.shipCityLabel.setObjectName("shipCityLabel")
        self.shippingAddressLayout.addWidget(self.shipCityLabel)
        self.shipCountryPostalLabel = QtWidgets.QLabel(parent=self.shippingAddressGroupBox)
        self.shipCountryPostalLabel.setWordWrap(True)
        self.shipCountryPostalLabel.setObjectName("shipCountryPostalLabel")
        self.shippingAddressLayout.addWidget(self.shipCountryPostalLabel)
        self.quoteContentLayout.addWidget(self.shippingAddressGroupBox)
        self.shippingOptionsGroupBox = QtWidgets.QGroupBox(parent=self.quoteContentPage)
        self.shippingOptionsGroupBox.setObjectName("shippingOptionsGroupBox")
        self.shippingOptionsLayout = QtWidgets.QVBoxLayout(self.shippingOptionsGroupBox)
        self.shippingOptionsLayout.setSpacing(6)
        self.shippingOptionsLayout.setObjectName("shippingOptionsLayout")
        self.quoteContentLayout.addWidget(self.shippingOptionsGroupBox)
        self.priceSummaryGroupBox = QtWidgets.QGroupBox(parent=self.quoteContentPage)
        self.priceSummaryGroupBox.setObjectName("priceSummaryGroupBox")
        self.priceSummaryLayout = QtWidgets.QVBoxLayout(self.priceSummaryGroupBox)
        self.priceSummaryLayout.setSpacing(6)
        self.priceSummaryLayout.setObjectName("priceSummaryLayout")
        self.productPriceRow = QtWidgets.QHBoxLayout()
        self.productPriceRow.setObjectName("productPriceRow")
        self.productPriceHeadLabel = QtWidgets.QLabel(parent=self.priceSummaryGroupBox)
        self.productPriceHeadLabel.setWordWrap(True)
        self.productPriceHeadLabel.setObjectName("productPriceHeadLabel")
        self.productPriceRow.addWidget(self.productPriceHeadLabel)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.productPriceRow.addItem(spacerItem3)
        self.productPriceLabel = QtWidgets.QLabel(parent=self.priceSummaryGroupBox)
        self.productPriceLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.productPriceLabel.setWordWrap(True)
        self.productPriceLabel.setObjectName("productPriceLabel")
        self.productPriceRow.addWidget(self.productPriceLabel)
        self.priceSummaryLayout.addLayout(self.productPriceRow)
        self.shippingPriceRow = QtWidgets.QHBoxLayout()
        self.shippingPriceRow.setObjectName("shippingPriceRow")
        self.shippingPriceHeadLabel = QtWidgets.QLabel(parent=self.priceSummaryGroupBox)
        self.shippingPriceHeadLabel.setWordWrap(True)
        self.shippingPriceHeadLabel.setObjectName("shippingPriceHeadLabel")
        self.shippingPriceRow.addWidget(self.shippingPriceHeadLabel)
        spacerItem4 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.shippingPriceRow.addItem(spacerItem4)
        self.shippingPriceLabel = QtWidgets.QLabel(parent=self.priceSummaryGroupBox)
        self.shippingPriceLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.shippingPriceLabel.setWordWrap(True)
        self.shippingPriceLabel.setObjectName("shippingPriceLabel")
        self.shippingPriceRow.addWidget(self.shippingPriceLabel)
        self.priceSummaryLayout.addLayout(self.shippingPriceRow)
        self.priceDivider = QtWidgets.QFrame(parent=self.priceSummaryGroupBox)
        self.priceDivider.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.priceDivider.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.priceDivider.setObjectName("priceDivider")
        self.priceSummaryLayout.addWidget(self.priceDivider)
        self.totalPriceRow = QtWidgets.QHBoxLayout()
        self.totalPriceRow.setObjectName("totalPriceRow")
        self.totalPriceHeadLabel = QtWidgets.QLabel(parent=self.priceSummaryGroupBox)
        self.totalPriceHeadLabel.setObjectName("totalPriceHeadLabel")
        self.totalPriceRow.addWidget(self.totalPriceHeadLabel)
        spacerItem5 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.totalPriceRow.addItem(spacerItem5)
        self.totalPriceLabel = QtWidgets.QLabel(parent=self.priceSummaryGroupBox)
        self.totalPriceLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.totalPriceLabel.setObjectName("totalPriceLabel")
        self.totalPriceRow.addWidget(self.totalPriceLabel)
        self.priceSummaryLayout.addLayout(self.totalPriceRow)
        self.currencyNoteLabel = QtWidgets.QLabel(parent=self.priceSummaryGroupBox)
        self.currencyNoteLabel.setWordWrap(True)
        self.currencyNoteLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.currencyNoteLabel.setObjectName("currencyNoteLabel")
        self.priceSummaryLayout.addWidget(self.currencyNoteLabel)
        self.quoteContentLayout.addWidget(self.priceSummaryGroupBox)
        spacerItem6 = QtWidgets.QSpacerItem(
            20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.quoteContentLayout.addItem(spacerItem6)
        self.dialogStackedWidget.addWidget(self.quoteContentPage)
        self.quoteErrorPage = QtWidgets.QWidget()
        self.quoteErrorPage.setObjectName("quoteErrorPage")
        self.quoteErrorLayout = QtWidgets.QVBoxLayout(self.quoteErrorPage)
        self.quoteErrorLayout.setSpacing(10)
        self.quoteErrorLayout.setObjectName("quoteErrorLayout")
        spacerItem7 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.quoteErrorLayout.addItem(spacerItem7)
        self.quoteErrorIconLabel = QtWidgets.QLabel(parent=self.quoteErrorPage)
        self.quoteErrorIconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.quoteErrorIconLabel.setObjectName("quoteErrorIconLabel")
        self.quoteErrorLayout.addWidget(self.quoteErrorIconLabel)
        self.quoteErrorTitleLabel = QtWidgets.QLabel(parent=self.quoteErrorPage)
        self.quoteErrorTitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.quoteErrorTitleLabel.setObjectName("quoteErrorTitleLabel")
        self.quoteErrorLayout.addWidget(self.quoteErrorTitleLabel)
        self.quoteErrorMessageLabel = QtWidgets.QLabel(parent=self.quoteErrorPage)
        self.quoteErrorMessageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.quoteErrorMessageLabel.setWordWrap(True)
        self.quoteErrorMessageLabel.setObjectName("quoteErrorMessageLabel")
        self.quoteErrorLayout.addWidget(self.quoteErrorMessageLabel)
        self.quoteRetryLayout = QtWidgets.QHBoxLayout()
        self.quoteRetryLayout.setObjectName("quoteRetryLayout")
        spacerItem8 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.quoteRetryLayout.addItem(spacerItem8)
        self.quoteRetryButton = QtWidgets.QPushButton(parent=self.quoteErrorPage)
        self.quoteRetryButton.setObjectName("quoteRetryButton")
        self.quoteRetryLayout.addWidget(self.quoteRetryButton)
        spacerItem9 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.quoteRetryLayout.addItem(spacerItem9)
        self.quoteErrorLayout.addLayout(self.quoteRetryLayout)
        spacerItem10 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.quoteErrorLayout.addItem(spacerItem10)
        self.dialogStackedWidget.addWidget(self.quoteErrorPage)
        self.rootLayout.addWidget(self.dialogStackedWidget)
        self.buttonsActions = QtWidgets.QDialogButtonBox(parent=AtlasPressQuoteDialog)
        self.buttonsActions.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonsActions.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.buttonsActions.setObjectName("buttonsActions")
        self.rootLayout.addWidget(self.buttonsActions)

        self.retranslateUi(AtlasPressQuoteDialog)
        self.dialogStackedWidget.setCurrentIndex(0)
        self.buttonsActions.accepted.connect(AtlasPressQuoteDialog.accept)  # type: ignore
        self.buttonsActions.rejected.connect(AtlasPressQuoteDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AtlasPressQuoteDialog)

    def retranslateUi(self, AtlasPressQuoteDialog):
        _translate = QtCore.QCoreApplication.translate
        AtlasPressQuoteDialog.setWindowTitle(
            _translate("AtlasPressQuoteDialog", "Atlas Press — Your Quote")
        )
        self.headerLabel.setText(_translate("AtlasPressQuoteDialog", "🗺️  Print & Order Your Map"))
        self.stepIndicatorLabel.setText(
            _translate("AtlasPressQuoteDialog", "Step 3 of 3 — Review Your Quote")
        )
        self.stepIndicatorLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "color: palette(text); font-size: 11px;")
        )
        self.dividerLine.setStyleSheet(_translate("AtlasPressQuoteDialog", "color: #dddddd;"))
        self.quoteLoadingTextLabel.setText(
            _translate("AtlasPressQuoteDialog", "Calculating your quote…")
        )
        self.quoteLoadingTextLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "color: palette(text); font-size: 12px;")
        )
        self.productSummaryGroupBox.setTitle(
            _translate("AtlasPressQuoteDialog", "Selected Product")
        )
        self.productSummaryGroupBox.setStyleSheet(
            _translate(
                "AtlasPressQuoteDialog", "QGroupBox { color: palette(text); font-weight: bold; }"
            )
        )
        self.productThumbnailLabel.setStyleSheet(
            _translate(
                "AtlasPressQuoteDialog",
                "background: #f0f0f0; border: 1px solid #e0e0e0; border-radius: 4px;",
            )
        )
        self.productNameLabel.setText(_translate("AtlasPressQuoteDialog", "Canvas Print"))
        self.productNameLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "font-weight: bold; font-size: 12px;")
        )
        self.productVariantLabel.setText(_translate("AtlasPressQuoteDialog", "—"))
        self.productVariantLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "color: palette(text); font-size: 11px;")
        )
        self.shippingAddressGroupBox.setTitle(_translate("AtlasPressQuoteDialog", "Shipping To"))
        self.shippingAddressGroupBox.setStyleSheet(
            _translate(
                "AtlasPressQuoteDialog", "QGroupBox { color: palette(text); font-weight: bold; }"
            )
        )
        self.shipNameLabel.setText(_translate("AtlasPressQuoteDialog", "—"))
        self.shipNameLabel.setStyleSheet(
            _translate(
                "AtlasPressQuoteDialog", "font-size: 12px; font-weight: bold; color: palette(text);"
            )
        )
        self.shipEmailLabel.setText(_translate("AtlasPressQuoteDialog", "—"))
        self.shipEmailLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "font-size: 11px; color: palette(text);")
        )
        self.shipAddressLabel.setText(_translate("AtlasPressQuoteDialog", "—"))
        self.shipAddressLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "font-size: 11px; color: palette(text);")
        )
        self.shipCityLabel.setText(_translate("AtlasPressQuoteDialog", "—"))
        self.shipCityLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "font-size: 11px; color: palette(text);")
        )
        self.shipCountryPostalLabel.setText(_translate("AtlasPressQuoteDialog", "—"))
        self.shipCountryPostalLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "font-size: 11px; color: palette(text);")
        )
        self.shippingOptionsGroupBox.setTitle(
            _translate("AtlasPressQuoteDialog", "Shipping Method")
        )
        self.shippingOptionsGroupBox.setStyleSheet(
            _translate(
                "AtlasPressQuoteDialog", "QGroupBox { color: palette(text); font-weight: bold; }"
            )
        )
        self.priceSummaryGroupBox.setTitle(_translate("AtlasPressQuoteDialog", "Price Summary"))
        self.priceSummaryGroupBox.setStyleSheet(
            _translate(
                "AtlasPressQuoteDialog", "QGroupBox { color: palette(text); font-weight: bold; }"
            )
        )
        self.productPriceHeadLabel.setText(_translate("AtlasPressQuoteDialog", "Product"))
        self.productPriceHeadLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "font-size: 12px; color: palette(text);")
        )
        self.productPriceLabel.setText(_translate("AtlasPressQuoteDialog", "—"))
        self.productPriceLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "font-size: 12px; color: palette(text);")
        )
        self.shippingPriceHeadLabel.setText(_translate("AtlasPressQuoteDialog", "Shipping"))
        self.shippingPriceHeadLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "font-size: 12px; color: palette(text);")
        )
        self.shippingPriceLabel.setText(_translate("AtlasPressQuoteDialog", "—"))
        self.shippingPriceLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "font-size: 12px; color: palette(text);")
        )
        self.priceDivider.setStyleSheet(_translate("AtlasPressQuoteDialog", "color: #dddddd;"))
        self.totalPriceHeadLabel.setText(_translate("AtlasPressQuoteDialog", "Total"))
        self.totalPriceHeadLabel.setStyleSheet(
            _translate(
                "AtlasPressQuoteDialog", "font-size: 13px; font-weight: bold; color: palette(text);"
            )
        )
        self.totalPriceLabel.setText(_translate("AtlasPressQuoteDialog", "—"))
        self.totalPriceLabel.setStyleSheet(
            _translate(
                "AtlasPressQuoteDialog", "font-size: 14px; font-weight: bold; color: #3a7ebf;"
            )
        )
        self.currencyNoteLabel.setText(
            _translate("AtlasPressQuoteDialog", "All prices in USD. Taxes may apply at checkout.")
        )
        self.currencyNoteLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "color: palette(text); font-size: 10px;")
        )
        self.quoteErrorIconLabel.setText(_translate("AtlasPressQuoteDialog", "⚠️"))
        self.quoteErrorIconLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "font-size: 28px;")
        )
        self.quoteErrorTitleLabel.setText(
            _translate("AtlasPressQuoteDialog", "Could not calculate quote")
        )
        self.quoteErrorTitleLabel.setStyleSheet(
            _translate(
                "AtlasPressQuoteDialog", "font-size: 13px; font-weight: bold; color: palette(text);"
            )
        )
        self.quoteErrorMessageLabel.setText(
            _translate("AtlasPressQuoteDialog", "Please check your shipping address and try again.")
        )
        self.quoteErrorMessageLabel.setStyleSheet(
            _translate("AtlasPressQuoteDialog", "color: palette(text); font-size: 11px;")
        )
        self.quoteRetryButton.setText(_translate("AtlasPressQuoteDialog", "Retry"))
        self.quoteRetryButton.setStyleSheet(
            _translate(
                "AtlasPressQuoteDialog",
                "QPushButton { background: #3a7ebf; color: white; border: none;\n"
                "              border-radius: 4px; padding: 6px 24px; font-size: 12px; }\n"
                "            QPushButton:hover { background: #2e6aaa; }",
            )
        )
